// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bounding_box
Rcpp::List bounding_box(Rcpp::IntegerVector runs, Rcpp::StringVector values, Rcpp::IntegerVector index1, Rcpp::StringVector ref_chr1, Rcpp::IntegerVector ref_start1, Rcpp::IntegerVector ref_end1, Rcpp::IntegerVector index2, Rcpp::StringVector ref_chr2, Rcpp::IntegerVector ref_start2, Rcpp::IntegerVector ref_end2, Rcpp::LogicalVector reflect);
RcppExport SEXP _GenomicInteractions_bounding_box(SEXP runsSEXP, SEXP valuesSEXP, SEXP index1SEXP, SEXP ref_chr1SEXP, SEXP ref_start1SEXP, SEXP ref_end1SEXP, SEXP index2SEXP, SEXP ref_chr2SEXP, SEXP ref_start2SEXP, SEXP ref_end2SEXP, SEXP reflectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type runs(runsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type index1(index1SEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type ref_chr1(ref_chr1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ref_start1(ref_start1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ref_end1(ref_end1SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type index2(index2SEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type ref_chr2(ref_chr2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ref_start2(ref_start2SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ref_end2(ref_end2SEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type reflect(reflectSEXP);
    rcpp_result_gen = Rcpp::wrap(bounding_box(runs, values, index1, ref_chr1, ref_start1, ref_end1, index2, ref_chr2, ref_start2, ref_end2, reflect));
    return rcpp_result_gen;
END_RCPP
}
// collate_2D_hits
Rcpp::List collate_2D_hits(Rcpp::IntegerVector query_indices_left, Rcpp::IntegerVector query_indices_right, Rcpp::IntegerVector query_hits_left, Rcpp::IntegerVector subject_hits_left, Rcpp::IntegerVector query_hits_right, Rcpp::IntegerVector subject_hits_right, Rcpp::IntegerVector subject_indices_left, Rcpp::IntegerVector subject_order_left, Rcpp::IntegerVector subject_indices_right, Rcpp::IntegerVector subject_order_right);
RcppExport SEXP _GenomicInteractions_collate_2D_hits(SEXP query_indices_leftSEXP, SEXP query_indices_rightSEXP, SEXP query_hits_leftSEXP, SEXP subject_hits_leftSEXP, SEXP query_hits_rightSEXP, SEXP subject_hits_rightSEXP, SEXP subject_indices_leftSEXP, SEXP subject_order_leftSEXP, SEXP subject_indices_rightSEXP, SEXP subject_order_rightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_indices_left(query_indices_leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_indices_right(query_indices_rightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_hits_left(query_hits_leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_hits_left(subject_hits_leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_hits_right(query_hits_rightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_hits_right(subject_hits_rightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_indices_left(subject_indices_leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_order_left(subject_order_leftSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_indices_right(subject_indices_rightSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_order_right(subject_order_rightSEXP);
    rcpp_result_gen = Rcpp::wrap(collate_2D_hits(query_indices_left, query_indices_right, query_hits_left, subject_hits_left, query_hits_right, subject_hits_right, subject_indices_left, subject_order_left, subject_indices_right, subject_order_right));
    return rcpp_result_gen;
END_RCPP
}
// expand_1D_hits
Rcpp::List expand_1D_hits(Rcpp::IntegerVector query_hits, Rcpp::IntegerVector subject_hits, Rcpp::IntegerVector query_indices, Rcpp::IntegerVector query_order, Rcpp::IntegerVector subject_indices, Rcpp::IntegerVector subject_order);
RcppExport SEXP _GenomicInteractions_expand_1D_hits(SEXP query_hitsSEXP, SEXP subject_hitsSEXP, SEXP query_indicesSEXP, SEXP query_orderSEXP, SEXP subject_indicesSEXP, SEXP subject_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_hits(query_hitsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_hits(subject_hitsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_indices(query_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type query_order(query_orderSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_indices(subject_indicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject_order(subject_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_1D_hits(query_hits, subject_hits, query_indices, query_order, subject_indices, subject_order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GenomicInteractions_bounding_box", (DL_FUNC) &_GenomicInteractions_bounding_box, 11},
    {"_GenomicInteractions_collate_2D_hits", (DL_FUNC) &_GenomicInteractions_collate_2D_hits, 10},
    {"_GenomicInteractions_expand_1D_hits", (DL_FUNC) &_GenomicInteractions_expand_1D_hits, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_GenomicInteractions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
