# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bounding_box <- function(runs, values, index1, ref_chr1, ref_start1, ref_end1, index2, ref_chr2, ref_start2, ref_end2, reflect) {
    .Call('_GenomicInteractions_bounding_box', PACKAGE = 'GenomicInteractions', runs, values, index1, ref_chr1, ref_start1, ref_end1, index2, ref_chr2, ref_start2, ref_end2, reflect)
}

collate_2D_hits <- function(query_indices_left, query_indices_right, query_hits_left, subject_hits_left, query_hits_right, subject_hits_right, subject_indices_left, subject_order_left, subject_indices_right, subject_order_right) {
    .Call('_GenomicInteractions_collate_2D_hits', PACKAGE = 'GenomicInteractions', query_indices_left, query_indices_right, query_hits_left, subject_hits_left, query_hits_right, subject_hits_right, subject_indices_left, subject_order_left, subject_indices_right, subject_order_right)
}

expand_1D_hits <- function(query_hits, subject_hits, query_indices, query_order, subject_indices, subject_order) {
    .Call('_GenomicInteractions_expand_1D_hits', PACKAGE = 'GenomicInteractions', query_hits, subject_hits, query_indices, query_order, subject_indices, subject_order)
}

